# Generated by Django 5.1.2 on 2024-10-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id_cine', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cine', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cines', to='appCine.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sala', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='appCine.cine')),
            ],
        ),
    ]
