# Generated by Django 4.1 on 2024-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='url_imagen',
            field=models.URLField(default='https://www.cultura.gob.es/.imaging/mte/mcd-theme/contenido-cim-ancho-2c/dam/mcd/cultura/areas/cine/mc/fe/imagenes-recurso/fachada-dore/jcr:content/fachada-dore.jpg'),
        ),
        migrations.AddField(
            model_name='sala',
            name='url_imagen',
            field=models.URLField(default='https://madridfilmoffice.com/wp-content/uploads/2018/10/Teatro-cine-capitol_-4.jpg'),
        ),
    ]
